export const moreRecipes: Array<[string, string, string, string]> = [
  ["Smoked Prime Rib", "Beef", "Standing rib roast, oak, a pink wall, and a hard crust.", "Pull it like steak, not like a packer. 125-130F is the job."],
  ["Smoked Beef Cheeks", "Beef", "The poor man's burnt end. Collagen until they slump.", "If they still chew like steak, they are not cheeks yet."],
  ["Smoked Picanha", "Beef", "Fat cap on, coarse salt, a hard sear after the smoke.", "Score the cap. Do not trim it off like a grocery roast."],
  ["Carolina Whole Hog", "Pork", "The whole animal, vinegar-pepper, pulled at the pit.", "If you sauce it red and sweet, you left the Carolinas."],
  ["Smoked Picnic Shoulder", "Pork", "The other end of the hog. Cheaper, messier, still pulls.", "Skin-on picnic needs heat or the hide never gives."],
  ["Country-Style Pork Ribs", "Pork", "Blade-end chunks, not true ribs. Treat them like little shoulders.", "They dry if you cook them like baby backs."],
  ["City Ham on the Pit", "Pork", "Cured ham, a little smoke, glaze at the end.", "It is already cooked. You are warming and barking it, not making bacon."],
  ["Spatchcock Pit Chicken", "Poultry", "Backbone out, flat on the grate, skin that can render.", "If it is sitting up like a grocery bird, the thighs lag the breast."],
  ["Smoked Chicken Wings", "Poultry", "Smoke first, then a hot kiss so the skin bites.", "Wings in a crowded pan steam. Give them room."],
  ["Competition Chicken Halves", "Poultry", "Half birds for the box when thighs are not the call.", "Skin schedule still rules. Color without leather."],
  ["Smoked Duck", "Poultry", "Fat under the skin that has to render or you served grease.", "Score the skin. Start warmer than brisket."],
  ["Smoked Quail", "Poultry", "Little birds, short smoke, hot finish.", "Five extra minutes and they are jerky."],
  ["Jalapeno Cheddar Sausage", "Sausage", "Coarse grind, visible cheese, a snap.", "Cheese melts out if the grind is lean or the fire is mean."],
  ["Texas Hot Links", "Sausage", "All-beef, chile-hot, snapped over oak.", "If there is no snap, you overcooked it or went too lean."],
  ["Pit-Smoked Trout", "Fish", "Whole trout, alder, a little salt and butter.", "Fish is done when it flakes. Chasing 160F wrecks it."],
  ["Cabrito Shoulder", "Mutton", "Young goat, oak, sliced or pulled.", "Goat goes dry. Fat and a mop are not optional."],
  ["Corn Pudding", "Sides", "Sweet corn, eggs, cream, a brown top.", "This sits next to brisket. Do not make it dessert-sweet."],
  ["Bread and Butter Pickles", "Sides", "Chips for the tray. Sweet-tart, not candy.", "Put them on pulled pork sandwiches."],
  ["Competition Box Garnish", "Sides", "Parsley or kale, clean and cold.", "Garnish is not salad. It frames the meat."],
  ["Competition Chicken Mop", "Sauces", "Thin, buttery, a little sweet. Built to lacquer skin.", "Mop late. Early sugar burns."],
  ["Peach Pit Sauce", "Sauces", "Ripe peach, vinegar, a little heat. For pork.", "Salt it like sauce, not like jam."],
  ["Cherry Cola Glaze", "Sauces", "Dark soda, cherry, reduced until it coats a rib.", "Reduce first. Raw soda on meat is a mess."],
  ["Butter Poultry Injection", "Sauces", "Melted butter, stock, salt. For turkey and thighs.", "Inject warm. Hot butter blows pockets and leaks."],
  ["Blackberry Cobbler", "Desserts", "Blackberries under biscuit batter in a hot skillet.", "Juice should bubble thick, not run like soup."],
  ["Cherry Cobbler", "Desserts", "Tart cherries, sugar, a browned top.", "If it tastes only sweet, you forgot the lemon."],
  ["Apple Crisp", "Desserts", "Sliced apples, oat streusel, pit heat.", "Keep the lid off at the end or the topping steams."],
  ["Sweet Potato Pie", "Desserts", "Roasted sweet potato, warm spice, a set slice.", "Cut it cool. Hot pie slumps."],
  ["Chocolate Chess Pie", "Desserts", "Cocoa custard in a crust. Dense on purpose.", "The center should just barely jiggle."],
  ["Texas Sheet Cake", "Desserts", "Thin chocolate cake, poured icing, pecans on top.", "Ice it hot so the frosting melts into the crumb."],
  ["Bourbon Bread Pudding", "Desserts", "Stale bread, custard, a bourbon soak.", "Dry bread first. Wet bread makes scrambled eggs."],
  ["Fried Peach Pies", "Desserts", "Hand pies, sealed tight, fried until blistered.", "A leak in the seal is a grease fire in a crust."],
  ["Cast-Iron Pineapple Cake", "Desserts", "Brown sugar, butter, rings, batter over the top.", "Flip it while it is hot or it welds to the iron."],
  ["Banana Pudding Pie", "Desserts", "The pudding in a crust when you want slices, not scoops.", "Bananas brown fast. Assemble close to service."],
  ["Pecan Pralines", "Desserts", "Sugar, cream, pecans, set on wax paper.", "Pull them when they sheen, not when they scorch."],
  ["Pit Smores", "Desserts", "Graham, chocolate, marshmallow, a lick of smoke.", "Thirty seconds too long and you served charcoal."]
];
