const recipeData = [
  ["Central Texas Brisket", "Beef"],
  ["Santa Maria Tri-Tip", "Beef"],
  ["Point Burnt Ends", "Beef"],
  ["Texas Plate Ribs", "Beef"],
  ["Poor Man's Brisket", "Beef"],
  ["Herb-Crusted Lamb Shoulder", "Beef"],
  ["Smoked Mississippi Pot Roast", "Beef"],
  ["Smoked BBQ Burger", "Beef"],
  ["Smoked Meatloaf", "Beef"],
  ["Championship Chili", "Beef"],

  ["Kansas City Spare Ribs", "Pork"],
  ["Eastern Carolina Pulled Pork", "Pork"],
  ["Memphis Dry Ribs", "Pork"],
  ["Pork Belly Burnt Ends", "Pork"],
  ["St. Louis Pork Steaks", "Pork"],
  ["Applewood Pork Loin", "Pork"],
  ["Applewood Smoked Bacon", "Pork"],
  ["Buckboard Bacon", "Pork"],
  ["Monroe County Shoulder", "Pork"],
  ["Florida Sweet Ribs", "Pork"],
  ["Mississippi Sweet Ribs", "Pork"],
  ["Copycat P.F. Chang's Spare Ribs", "Pork"],
  ["Dry Rub Spare Ribs", "Pork"],
  ["Championship Pulled Pork", "Pork"],

  ["Alabama White Sauce Chicken", "Poultry"],
  ["Competition Chicken Thighs", "Poultry"],
  ["Herb-Butter Smoked Turkey", "Poultry"],

  ["Smoked Venison Backstrap", "Venison"],
  ["Amish Pulled Venison", "Venison"],
  ["Kentucky Burgoo", "Venison"],

  ["Owensboro Mutton", "Mutton"],
  ["Whole Smoked Gator", "Gator"],
  ["Cedar-Plank Salmon", "Fish"],
  ["Texas Hot Guts", "Sausage"],

  ["Pit Beans with Brisket Trim", "Sides"],
  ["Cast-Iron Smoked Mac", "Sides"],
  ["Pepper Vinegar Slaw", "Sides"],
  ["Mustard Potato Salad", "Sides"],
  ["Pit Pickled Onions", "Sides"],
  ["Smoked Cabbage Wedges", "Sides"],
  ["Cast-Iron Cornbread", "Sides"],
  ["Memphis BBQ Spaghetti", "Sides"],
  ["Potlikker Collards", "Sides"],
  ["Hush Puppies", "Sides"],
  ["Smoked Creamed Corn", "Sides"],
  ["Santa Maria Pinquito Beans", "Sides"],
  ["Alabama Cheese Grits", "Sides"],
  ["Pit Pimento Cheese", "Sides"],
  ["Hatch Street Corn", "Sides"],
  ["Cajun Dirty Rice", "Sides"],

  ["Santa Maria Seasoning", "Rubs"],
  ["Memphis Dry Rub", "Rubs"],
  ["Cajun Pit Rub", "Rubs"],
  ["Hatch Chile Cumin Rub", "Rubs"],
  ["Chicago Rib-Tip Rub", "Rubs"],
  ["Maryland Pit-Beef Rub", "Rubs"],
  ["Alder Brown-Sugar Rub", "Rubs"],
  ["Ember House Rub", "Rubs"],
  ["Sweet Rib Rub", "Rubs"],
  ["Barbecue Seasoning", "Rubs"],
  ["Dalmatian Rub", "Rubs"],
  ["SPG House Rub", "Rubs"],
  ["Competition Pork Rub", "Rubs"],
  ["Coffee-Chile Beef Rub", "Rubs"],
  ["Lemon-Pepper Poultry Rub", "Rubs"],

  ["East Texas Sweet Sauce", "Sauces"],
  ["Thin Chile Mop", "Sauces"],
  ["South Texas Pit Salsa", "Sauces"],
  ["Kentucky Black BBQ Sauce", "Sauces"],
  ["Florida Sweet Sauce", "Sauces"],
  ["Mississippi Sweet Sauce", "Sauces"],
  ["Ember Molasses Sauce", "Sauces"],
  ["Ember Smoke Sauce", "Sauces"],
  ["Sweet Vinegar Sauce", "Sauces"],
  ["Raspberry Chipotle Sauce", "Sauces"],
  ["Chicago Mild (and Hot)", "Sauces"],
  ["Maryland Tiger Sauce", "Sauces"],
  ["New Mexico Red Chile", "Sauces"],
  ["Cajun Butter Mop", "Sauces"],
  ["Blackberry Pit Sauce", "Sauces"],
  ["Kansas City Molasses Sauce", "Sauces"],
  ["Eastern Vinegar-Pepper Sauce", "Sauces"],
  ["Carolina Gold Mustard Sauce", "Sauces"],
  ["Alabama White Sauce", "Sauces"],
  ["Lexington Dip", "Sauces"],
  ["Memphis Barbecue Sauce", "Sauces"],
  ["Championship Pork Injection", "Sauces"],

  ["Pit Banana Pudding", "Desserts"],
  ["Skillet Peach Cobbler", "Desserts"],
  ["Texas Pecan Pie", "
