export const listA: Array<[string, string, string, string]> = [
  ["Central Texas Brisket", "Beef", "Salt, pepper, post oak, and patience. The packer is the whole argument.", "If the smoke is white and thick, you are burning fuel, not cooking beef."],
  ["Santa Maria Tri-Tip", "Beef", "Live oak, a hard sear, and a medium-rare center.", "Slice against the grain — this cut changes direction mid-roast. Serve with pinquito beans."],
  ["Point Burnt Ends", "Beef", "The point after the packer is done. Cubed, sauced, and caramelized.", "If they look wet in the pan, give them more time, not more sauce."],
  ["Texas Plate Ribs", "Beef", "Dino bones. Thick, greasy in the right way, and loud on the plate.", "Done by feel. If the probe drags, they are not ready."],
  ["Poor Man's Brisket", "Beef", "Chuck roast cooked like a packer when the bank account says no.", "Chuck has more seams than a flat. Slice across them or chop it."],
  ["Herb-Crusted Lamb Shoulder", "Beef", "Shoulder on smoke with rosemary, garlic, and lemon.", "Lamb fat goes rancid-fast on a dirty fire. Keep the smoke thin."],
  ["Smoked Mississippi Pot Roast", "Beef", "Ranch, pepperoncini, and butter — but the roast sees smoke first.", "If you start it in the pan, it is just a pot roast with ambition."],
  ["Smoked BBQ Burger", "Beef", "The grind gets oak and a mop of sauce at the end.", "Do not overwork the grind. Tight patties eat like meatloaf."],
  ["Smoked Meatloaf", "Beef", "A loaf that can take smoke without falling apart.", "Rack it. A pan of grease steams the loaf."],
  ["Championship Chili", "Beef", "No beans in the contest pot. Smoke the meat, then stew it.", "Beans are a side, not an ingredient, if you are turning this in."],
  ["Kansas City Spare Ribs", "Pork", "St. Louis trim, sweet bark, late glaze that shines without pooling.", "The bone should twist with a tug, not fall out like boiled meat."],
  ["Eastern Carolina Pulled Pork", "Pork", "Whole shoulder, vinegar-pepper, no ketchup in the building.", "If it tastes sweet, you left the Carolinas."],
  ["Memphis Dry Ribs", "Pork", "No glaze. The rub is the finish.", "Wet ribs are a different city. Keep the bottle off the box."],
  ["Pork Belly Burnt Ends", "Pork", "Cubed belly, rendered, then candy-glazed.", "Underrendered belly tastes like warm lard. Give it time before the glaze."],
  ["St. Louis Pork Steaks", "Pork", "Shoulder steaks over coals, mopped until they slump.", "This is tavern meat. Do not plate it like a tasting menu."],
  ["Applewood Pork Loin", "Pork", "Lean roast. Pull it early or it dies.", "145°F is cooked. Chasing 160°F invents sawdust."],
  ["Applewood Smoked Bacon", "Pork", "Belly, cure, smoke. Slice it yourself.", "No pink salt, no bacon. Do not freestyle the cure math."],
  ["Buckboard Bacon", "Pork", "Cured pork loin smoked like bacon.", "This overcooks in a blink. Watch the probe."],
  ["Monroe County Shoulder", "Pork", "West Kentucky shoulder dipped in a thin pepper dip.", "If it tastes like Kansas City, you missed Monroe County."],
  ["Florida Sweet Ribs", "Pork", "Sunshine-sweet glaze, a little citrus, still needs bark.", "Sweet is the finish, not the first hour."],
  ["Mississippi Sweet Ribs", "Pork", "Delta sweet, a little heat, pork that still tastes like pork.", "If the sauce is the only flavor, you under-seasoned the meat."],
  ["Copycat P.F. Chang's Spare Ribs", "Pork", "Sticky, salty-sweet, a little char.", "Dry the ribs before the glaze or it slides off."],
  ["Dry Rub Spare Ribs", "Pork", "No wrap, no sauce. Rub and smoke.", "Wrapping is a tool, not a requirement."],
  ["Championship Pulled Pork", "Pork", "Injected butt, layered rub, box-ready strands.", "Turn-in meat should be moist without sitting in a puddle."],
  ["Alabama White Sauce Chicken", "Poultry", "Smoked bird, then a slather of mayo-horseradish-pepper sauce.", "White sauce is a finishing dip, not a marinade. Do not heat it."],
  ["Competition Chicken Thighs", "Poultry", "Skin schedule, even color, bite-through, no leather.", "If the skin is rubber, you rushed the render."],
  ["Herb-Butter Smoked Turkey", "Poultry", "Butter under the skin, smoke that does not taste like an ashtray.", "Low-and-slow turkey invents beige wood. Give it heat."],
  ["Smoked Venison Backstrap", "Venison", "The tenderloin of the woods. Treat it like a good steak.", "Past medium and you are making jerky with extra steps."],
  ["Amish Pulled Venison", "Venison", "Shoulder or neck, low smoke, fat added back.", "Venison has no spare fat. You have to bring some."],
  ["Kentucky Burgoo", "Venison", "The stew that will take whatever walked through the fence.", "Burgoo is leftovers with a backbone. Do not make it pretty."],
  ["Owensboro Mutton", "Mutton", "Western Kentucky mutton and black dip.", "Young lamb and sweet sauce is a different state."],
  ["Whole Smoked Gator", "Gator", "Gulf yard bird. Brine it or the tail turns to rope.", "Dry gator cannot be sauced back to life."],
  ["Cedar-Plank Salmon", "Fish", "Plank, alder, brown sugar, and a fish that still flakes.", "A dry plank flames. Soak it."],
  ["Texas Hot Guts", "Sausage", "Coarse beef sausage, chile-hot, snapped over oak.", "If the snap is gone, you overcooked it or used lean grind."],
  ["Pit Beans with Brisket Trim", "Sides", "Beans that ate the leftover bark.", "Sweet beans are dessert. These should taste like the brisket plate."],
  ["Cast-Iron Smoked Mac", "Sides", "Cheese sauce in iron, a little smoke, a brown top.", "Too much smoke turns cheese bitter."],
  ["Pepper Vinegar Slaw", "Sides", "No mayo. Cabbage that can sit next to fat pork.", "This is for the pork tray, not a picnic buffet."],
  ["Mustard Potato Salad", "Sides", "Warm potatoes, yellow mustard, pickle bite.", "If it tastes only like mayo, you made the wrong potato salad."],
  ["Pit Pickled Onions", "Sides", "Red onions, hot vinegar, ready when the ribs rest.", "Put these on brisket sandwiches and watch people shut up."],
  ["Smoked Cabbage Wedges", "Sides", "Wedges on the grate with butter and pepper.", "Leave the core so the wedge stays a wedge."],
  ["Cast-Iron Cornbread", "Sides", "Hot iron, bacon drippings, a brown crust that scrapes.", "If you add a lot of sugar, call it cake."],
  ["Memphis BBQ Spaghetti", "Sides", "Pork, spaghetti, and barbecue sauce in a pan.", "This is not Italian. Stop looking for basil."],
  ["Potlikker Collards", "Sides", "Greens on a ham hock until the pot liquor is the point.", "Save the potlikker. That is the sauce."],
  ["Hush Puppies", "Sides", "Cornmeal orbs fried next to the pit.", "Greasy pups sat in cool oil."],
  ["Smoked Creamed Corn", "Sides", "Corn, cream, a kiss of smoke.", "Twenty minutes of smoke is plenty."],
];
