export const listB: Array<[string, string, string, string]> = [
  ["Santa Maria Pinquito Beans", "Sides", "Small pink beans, bacon, chile. The tri-tip’s other half.", "Navy beans will not do."],
  ["Alabama Cheese Grits", "Sides", "Stone-ground, cheddar, salt enough for white-sauce chicken.", "Instant grits are a different and worse food."],
  ["Pit Pimento Cheese", "Sides", "Sharp cheddar, pimentos, mayo, a little heat.", "Pre-shredded cheese will not melt into the spread right."],
  ["Hatch Street Corn", "Sides", "Corn on the grate, Hatch chile, lime, cotija.", "Bland corn is a wasted grate."],
  ["Cajun Dirty Rice", "Sides", "Liver, sausage, trinity.", "If there is no liver, it is just rice with sausage."],
  ["Santa Maria Seasoning", "Rubs", "Salt, garlic, pepper, parsley.", "Fresh garlic burns. Granulated belongs in the rub."],
  ["Memphis Dry Rub", "Rubs", "Paprika-forward, brown sugar in check.", "Too much sugar and a dry rib becomes a sticky rib by accident."],
  ["Cajun Pit Rub", "Rubs", "Paprika, cayenne, garlic, thyme.", "Cayenne stacks. Taste before you bury a bird in it."],
  ["Hatch Chile Cumin Rub", "Rubs", "Dried Hatch, cumin, salt.", "If the chile is mild, add chipotle rather than more salt."],
  ["Chicago Rib-Tip Rub", "Rubs", "For the cheap cut Chicago turned into a religion.", "Celery salt is the Chicago tell. Leave it in."],
  ["Maryland Pit-Beef Rub", "Rubs", "For roast beef over coals, sliced thin.", "Pit beef is medium-rare. Do not cook the rub to death."],
  ["Alder Brown-Sugar Rub", "Rubs", "For salmon and pork loin.", "Sugar burns. This is a short-cook rub."],
  ["Ember House Rub", "Rubs", "Salt-forward, pepper-heavy, a little sugar and chile.", "If the meat is already injected, back this off."],
  ["Sweet Rib Rub", "Rubs", "More brown sugar, still enough salt to count.", "Keep the pit under 275°F or the sugar goes bitter."],
  ["Barbecue Seasoning", "Rubs", "All-purpose shaker for weeknight chops.", "The pantry bottle, not the contest bottle."],
  ["Dalmatian Rub", "Rubs", "Salt and pepper. That is the whole sermon.", "Add ten spices and you made a different rub."],
  ["SPG House Rub", "Rubs", "Salt, pepper, garlic.", "Granulated garlic, not garlic salt."],
  ["Competition Pork Rub", "Rubs", "Built for butts and ribs that have to taste loud in one bite.", "Layer it: a coat, a rest, another coat."],
  ["Coffee-Chile Beef Rub", "Rubs", "Espresso, chile, salt. For plate ribs and the point.", "Use coffee, not a flavored latte grind."],
  ["Lemon-Pepper Poultry Rub", "Rubs", "The chicken-box perfume. Bright, not soapy.", "Bottled lemon pepper is already salty."],
  ["East Texas Sweet Sauce", "Sauces", "Tomato-sweet with a little heat.", "Central Texas can skip this. East Texas should not."],
  ["Thin Chile Mop", "Sauces", "A mop, not a coat.", "If it is thick, it is sauce. Thin it."],
  ["South Texas Pit Salsa", "Sauces", "Fire-roasted tomato and chile.", "Leave some char. That is the smoke."],
  ["Kentucky Black BBQ Sauce", "Sauces", "Worcestershire-heavy dip for mutton.", "Steak sauce that went to church in Owensboro."],
  ["Florida Sweet Sauce", "Sauces", "Citrus in the sweetness.", "Orange juice burns. Glaze late."],
  ["Mississippi Sweet Sauce", "Sauces", "Sweeter than Carolina, hotter than a picnic sauce.", "Taste it on pork, not on a spoon."],
  ["Ember Molasses Sauce", "Sauces", "House red. Molasses, vinegar, a little heat.", "Stop when it is deep, not black."],
  ["Ember Smoke Sauce", "Sauces", "Thinner, more pepper, for burgers and ends.", "If you cannot brush it, thin with vinegar."],
  ["Sweet Vinegar Sauce", "Sauces", "Halfway between Lexington and a picnic sauce.", "Warm meat drinks this."],
  ["Raspberry Chipotle Sauce", "Sauces", "Fruit and smoke for pork.", "One chipotle first."],
  ["Chicago Mild (and Hot)", "Sauces", "Mild for the table, hot for the people who asked.", "Serve both."],
  ["Maryland Tiger Sauce", "Sauces", "Horseradish and mayo heat for pit beef.", "Make it the day you serve it."],
  ["New Mexico Red Chile", "Sauces", "Red chile puree. Not ketchup with chili powder.", "Dusty taste means old chiles."],
  ["Cajun Butter Mop", "Sauces", "Butter, cayenne, lemon, garlic.", "Butter burns. Mop, do not pool it."],
  ["Blackberry Pit Sauce", "Sauces", "Dark fruit for pork.", "Salt it like a sauce, not like jam."],
  ["Kansas City Molasses Sauce", "Sauces", "The thick red people mean when they say barbecue sauce.", "Brush late or it scorches."],
  ["Eastern Vinegar-Pepper Sauce", "Sauces", "The whole Eastern Carolina argument in a jar.", "No tomato. Tomato is Lexington."],
  ["Carolina Gold Mustard Sauce", "Sauces", "South Carolina mustard. Tang first.", "This belongs on pork. It will fight brisket."],
  ["Alabama White Sauce", "Sauces", "Mayo, vinegar, pepper, horseradish.", "If you simmer this it breaks."],
  ["Lexington Dip", "Sauces", "Western NC vinegar-pepper with a little ketchup.", "It should still taste like vinegar."],
  ["Memphis Barbecue Sauce", "Sauces", "Tangier than KC, still red.", "On dry ribs this is a table sauce, not a mop."],
  ["Championship Pork Injection", "Sauces", "The juice that keeps a butt moist after a long smoke.", "If juice rivers off the board, you injected too fast."],
  ["Pit Banana Pudding", "Desserts", "Wafers, banana, soft custard. Cold after hot meat.", "Assemble close to service or the wafers turn to mush."],
  ["Skillet Peach Cobbler", "Desserts", "Peaches in iron with batter that rises around them.", "Ice cream is not optional unless you are out of ice cream."],
  ["Texas Pecan Pie", "Desserts", "Dark, set, pecans on top. Not a sugar puddle.", "Cut it cool. A hot pecan pie slumps like a bad brisket wrap."],
];
